### PR TITLE
add enterprise-acta-webapp

### PR DESCRIPTION
**Pull request by danp**
Adds `onebusaway-enterprise-acta-webapp` (i.e., v2 of the web UI) to the mix.

For deployments of v2 interface see:
* Tampa - http://tampa.onebusaway.org/enterprise/
* Puget Sound - http://pugetsound.onebusaway.org/enterprise/

Some configuration instructions:
https://github.com/OneBusAway/onebusaway-application-modules/wiki/Enterprise-Webapp-Configuration

### CODE REVIEW

**Comment by danp** [comment]
Doesn't currently work due to bean config issue but I'm having trouble figuring out what's missing.

**Comment by danp** [comment]
Currently failing in travis [here](https://travis-ci.org/OneBusAway/onebusaway-docker/builds/334428635#L2218) with:

```
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'searchServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.onebusaway.geocoder.enterprise.services.EnterpriseGeocoderService org.onebusaway.presentation.impl.search.SearchServiceImpl._geocoderService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No matching bean of type [org.onebusaway.geocoder.enterprise.services.EnterpriseGeocoderService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

**Comment by barbeau** [comment]
I believe this means you're missing an entry for `searchServiceImpl`in data-sources, but this is new in v2, so I don't know what it's supposed to contain.

**Comment by danp** [comment]
Did some digging but wasn't able to find any examples to build on. Maybe @sheldonabrown could offer a hint?

**Comment by sheldonabrown** [comment]
You missed two beans in the config instructions:  "externalGeocoderImpl" and "serviceAreaServiceImpl".  Scroll to the last snippet.

https://github.com/OneBusAway/onebusaway-application-modules/wiki/Enterprise-Webapp-Configuration

They can both be empty beans to get started, but do need to be present.

**Comment by danp** [comment]
Thanks!

Hmm, the config added by this PR already has both externalGeocoderImpl and serviceAreaServiceImpl entries, pretty sure I copied the config at the bottom of https://github.com/OneBusAway/onebusaway-application-modules/wiki/Enterprise-Webapp-Configuration to get started.

Should one of those be creating the searchServiceImpl bean that error messages mention?

**Comment by danp** [comment]
Got this green!

However, it probably only does the bare minimum to load the UI. Visiting a route page doesn't properly load the Google Map, for example, since there are no API keys. That will follow!

**Comment by barbeau** [comment]
🎉

**Pull request merged**
