### PR TITLE
add api-webapp

### LINKED ISSUE #3: Get onebusaway-api-webapp working with /bundle
Building on #2, add onebusaway-api-webapp using the bundle directory at `/bundle`. It should successfully respond to an http request to `/onebusaway-api-webapp/api/where/config.json?key=TEST` or similar.

### PR DESCRIPTION
**Pull request by danp**
This is where it should get fun!

Config based on https://github.com/OneBusAway/onebusaway-application-modules/wiki/Enterprise-Webapp-Configuration plus tips from email and slack.

Fixes #3

### CODE REVIEW

**Comment by danp** [comment]
Travis should dump logs/errors to look at to help figure out what's going on.

**Comment by barbeau** [comment]
I just explicitly set the Hibernate Dialect for HSQLDB in https://github.com/OneBusAway/onebusaway-docker/pull/5/commits/c448e1683c75e1595c21d66ac3ed434c2239f7fa to try and address Travis log at https://travis-ci.org/OneBusAway/onebusaway-docker/builds/332784717#L2132 that says:

~~~
Error creating bean with name 'agencyMetadataSessionFactory' defined in class path resource [data-sources.xml]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Hibernate Dialect must be explicitly set
~~~

As @sheldonabrown says this probably isn't the issue, but now we'll know for sure...

**Comment by barbeau** [comment]
Yup, no love.

@danp Are the following both expected in the travis logs?

* `Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing commit 18708eda27327fc4acec1f53d2b4571baa7fd0fc`
* `[ConfigurationServiceClientFileImpl.java:138] : Failed to get configuration out of /var/lib/oba/config.json, continuing without it.
java.io.FileNotFoundException: File '/var/lib/oba/config.json' does not exist`

**Comment by danp** [comment]
Yeah, the first bit is because the Dockerfile is doing `git clone --depth=1` so there are no past commits around to see what the last tag was. Both that and the second bit were present in #4 so seems fine, at least for now.

**Comment by barbeau** [comment]
Ok - I'm trying switching to `mvn package` in https://github.com/OneBusAway/onebusaway-docker/pull/5/commits/11b86aa12e816e3ea65a476008cceddacfb870c4 now...

**Comment by barbeau** [comment]
No luck, reverting back to `mvn install`.

@danp Here's the first SEVERE error I see in the Travis logs:

~~~
25-Jan-2018 20:54:46.854 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
25-Jan-2018 20:54:46.855 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/onebusaway-api-webapp] startup failed due to previous errors
~~~

For `Full details will be found in the appropriate container log file` - can you dump the container log file as well?  I don't believe we're seeing that (?)...

**Comment by danp** [comment]
Yeah, this PR has bin/ci dump the tomcat logs as well, for example [here](https://travis-ci.org/OneBusAway/onebusaway-docker/builds/333452209#L2151). That is where we get this from:

```
Error creating bean with name 'sessionFactory' defined in class path resource [org/onebusaway/container/application-context-hibernate.xml]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Hibernate Dialect must be explicitly set
```

So my take is the `Context [/onebusaway-api-webapp] startup failed due to previous errors` bit is in the tomcat stdout which means it failed to start due to the output from the tomcat logs.

**Comment by barbeau** [comment]
Is there a separate log file for HSQLDB?  It's been a while since I ran this setup myself.  If so we might want to try and dump that to see if it contains anything useful.

**Comment by barbeau** [comment]
FYI - I just removed the explicit reference to the Hibernate Dialect via https://github.com/OneBusAway/onebusaway-docker/pull/5/commits/6b9fe88dc77a0dc29ab03da3b301eb32eddc9f44 that I added earlier

**Comment by barbeau** [comment]
FYI, looks like this should fix the `java.lang.RuntimeException: Unable to find commits until some tag` error message:
https://github.com/ktoso/maven-git-commit-id-plugin/issues/61#issuecomment-68037525

**Comment by barbeau** [comment]
I added support for `TEST` API key and API keys for all native apps in https://github.com/OneBusAway/onebusaway-docker/pull/5/commits/2b6303409ae2f1114921583f22773a73897986c7 (I accidentally hit a keyboard key while editing on Github and mistakenly committed https://github.com/OneBusAway/onebusaway-docker/pull/5/commits/52ba86eee1f77126f803f1db74fbf20a587039fe, which is just the TEST API key).

**Comment by barbeau** [comment]
Didn't realize that `apiKeyValidationService` was already defined in data-sources, so I just removed the duplicate in https://github.com/OneBusAway/onebusaway-docker/pull/5/commits/bb673d9f4c8ae1aee75b9505d66afa5b02c55f3f.

**Comment by barbeau** [comment]
Just changed all `dataSources` to match transit-data-fed-webapp in https://github.com/OneBusAway/onebusaway-docker/pull/5/commits/d8ddc30b447be04de22c7c4b38b50dfcb35463dd to see if that works for HSQLDB

**Comment by barbeau** [comment]
Got database lock error (https://travis-ci.org/OneBusAway/onebusaway-docker/builds/333858474#L1247), so I'm reverting to make `dataSources` different again in https://github.com/OneBusAway/onebusaway-docker/pull/5/commits/427150fc5da9107a8149ed8687f929b540e1f793.

**Pull request merged**
