### PR TITLE
Make Dockerfile and docker-compose.yml work with 2.0.1-SNAPSHOT

### LINKED ISSUE #15: Build issues
Hi,

Build fails from Docker-Compose:

Step 4/19 : RUN mvn install     --quiet         -D license.skip=true    -D maven.test.skip=true
 ---> Running in 159b2190ee29
[ERROR] Unable to find commits until some tag
java.lang.RuntimeException: Unable to find commits until some tag
    at pl.project13.jgit.JGitCommon.findCommitsUntilSomeTag (JGitCommon.java:268)
    at pl.project13.jgit.DescribeCommand.call (DescribeCommand.java:277)
    at pl.project13.maven.git.JGitProvider.getGitDescribe (JGitProvider.java:221)
    at pl.project13.maven.git.JGitProvider.getGitDescribe (JGitProvider.java:117)
    at pl.project13.maven.git.GitDataProvider.maybePutGitDescribe (GitDataProvider.java:167)
    at pl.project13.maven.git.GitDataProvider.loadGitData (GitDataProvider.java:120)
    at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit (GitCommitIdMojo.java:588)
    at pl.project13.maven.git.GitCommitIdMojo.loadGitData (GitCommitIdMojo.java:555)
    at pl.project13.maven.git.GitCommitIdMojo.execute (GitCommitIdMojo.java:376)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.jgit.errors.RevWalkException: Walk failure.
    at org.eclipse.jgit.revwalk.RevWalk.iterator (RevWalk.java:1325)
    at pl.project13.jgit.JGitCommon.findCommitsUntilSomeTag (JGitCommon.java:256)
    at pl.project13.jgit.DescribeCommand.call (DescribeCommand.java:277)
    at pl.project13.maven.git.JGitProvider.getGitDescribe (JGitProvider.java:221)
    at pl.project13.maven.git.JGitProvider.getGitDescribe (JGitProvider.java:117)
    at pl.project13.maven.git.GitDataProvider.maybePutGitDescribe (GitDataProvider.java:167)
    at pl.project13.maven.git.GitDataProvider.loadGitData (GitDataProvider.java:120)
    at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit (GitCommitIdMojo.java:588)
    at pl.project13.maven.git.GitCommitIdMojo.loadGitData (GitCommitIdMojo.java:555)
    at pl.project13.maven.git.GitCommitIdMojo.execute (GitCommitIdMojo.java:376)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing commit 2a254845fa4c0192908f6dc770a7cd23fc9fbe66
    at org.eclipse.jgit.internal.storage.file.WindowCursor.open (WindowCursor.java:147)
    at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes (RevWalk.java:903)
    at org.eclipse.jgit.revwalk.RevCommit.parseHeaders (RevCommit.java:150)
    at org.eclipse.jgit.revwalk.PendingGenerator.next (PendingGenerator.java:147)
    at org.eclipse.jgit.revwalk.StartGenerator.next (StartGenerator.java:184)
    at org.eclipse.jgit.revwalk.RevWalk.next (RevWalk.java:435)
    at org.eclipse.jgit.revwalk.RevWalk.iterator (RevWalk.java:1323)
    at pl.project13.jgit.JGitCommon.findCommitsUntilSomeTag (JGitCommon.java:256)
    at pl.project13.jgit.DescribeCommand.call (DescribeCommand.java:277)
    at pl.project13.maven.git.JGitProvider.getGitDescribe (JGitProvider.java:221)
    at pl.project13.maven.git.JGitProvider.getGitDescribe (JGitProvider.java:117)
    at pl.project13.maven.git.GitDataProvider.maybePutGitDescribe (GitDataProvider.java:167)
    at pl.project13.maven.git.GitDataProvider.loadGitData (GitDataProvider.java:120)
    at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit (GitCommitIdMojo.java:588)
    at pl.project13.maven.git.GitCommitIdMojo.loadGitData (GitCommitIdMojo.java:555)
    at pl.project13.maven.git.GitCommitIdMojo.execute (GitCommitIdMojo.java:376)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

### PR DESCRIPTION
**Pull request by brodyFlannigan**
This fixes the issue raised in #15.

Fixes #15.

### CODE REVIEW

**Comment by brodyFlannigan** [comment]
Closing and re-opening to restart Travis.
I had forgotten to edit the bin/ci script

**Comment by barbeau** [comment]
Hmmm...Travis failed with this:

~~~
Successfully tagged oba-ci:latest
=== building bundle
=== running postgres
Unable to find image 'postgres:10' locally
10: Pulling from library/postgres
Status: Downloaded newer image for postgres:10
745c03a797d5a74ff9b2801d4d92be6a8e97b84b8e3aaefa7458cd573739e751
=== creating postgres database
Error response from daemon: No such container: oba-postgres
Error: No such container: oba-postgres
Error: No such container: oba-postgres
Error: No such container: oba-postgres
Error: No such container: oba-postgres
Error: No such container: oba-postgres
Error: No such container: oba-postgres
Error: No such container: oba-postgres
Error: No such container: oba-postgres
Error: No such container: oba-postgres
postgres didn't work
The command "bin/ci" exited with 1.
~~~

**Comment by brodyFlannigan** [comment]
I find that quite odd.
I only changed 2.0.0-SNAPSHOT to 2.0.1-SNAPSHOT.

I can't see why it would fail...

**Comment by barbeau** [comment]
For some reason I can't restart the Travis build directly on Travis, so I'm closing and re-opening to restart the build to see if it was an intermittent issue.

**Comment by barbeau** [comment]
Nope, same failure again in https://travis-ci.org/github/OneBusAway/onebusaway-docker/builds/680634315. 🤔

**Comment by barbeau** [comment]
To see if this is something external, I'm going to restart this build, which previously passed prior to merge into the master branch:
https://travis-ci.org/github/OneBusAway/onebusaway-docker/builds/559059670

**Comment by barbeau** [comment]
Well, that didn't work because we're checking out the master branch and the whole 2.0.1 issue...

**Comment by brodyFlannigan** [comment]
It could very well be my fault as I am new to this "pull request" business...

All I know is that once I made the changes to my files docker composed flawlessly when I told it `docker compose up build-bundle`...

**Comment by barbeau** [comment]
@dudebrains01 I think your PR is fine, there seems to be something else going on preventing CI from working with postgres.

If this works for you locally, I'm inclined to merge and figure out what's going on with CI separately. Master branch of this project is definitely broken due to the version changes in oba-app-modules and that needs to be fixed.

**Pull request merged**
